language: node_js
node_js:
  - 10
install:
  - yarn
script:
  - unset CI
  - yarn build
cache: yarn
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
